
apiVersion: v1
kind: Secret
metadata:
  name: ecommerce-secrets
  namespace: ecommerce
type: Opaque
stringData:


  JWT_SECRET_KEY: "dev-secret-key-32-chars-minimum-xx"


  USER_DB_PASSWORD: "postgres"
  PRODUCT_DB_PASSWORD: "postgres"
  ORDER_DB_PASSWORD: "postgres"

  USER_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@user-postgres.ecommerce.svc.cluster.local:5432/users_db"
  PRODUCT_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@product-postgres.ecommerce.svc.cluster.local:5432/products_db"
  ORDER_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@order-postgres.ecommerce.svc.cluster.local:5432/orders_db"